'use client';
import { useEffect,useRef,useState } from 'react';
import { Popcorn,Clapperboard,Plus,X,ArrowRight,Play,Lightbulb,Trophy,Volume2,VolumeX,HelpCircle,LogOut,Sparkles,Check,RotateCcw,Clock,Ticket,Film,LoaderCircle } from 'lucide-react';
type Game={id:string,players:{name:string,score:number}[],preferences:string,rounds:number,hintLimit:number,timerSeconds:number,index:number,ended:boolean,error?:string,queue:number,card:null|{id:string,status:string,error?:string,image:string|null,hints:string[],revealed:boolean,solved:boolean,awarded:boolean,answer:null|{title:string,year:number,explanation:string}}};
const avatars=['🍿','😎','🌻','🚀','🍒','🐯','🪩','🎸'];
export default function Home(){
 const [names,setNames]=useState(['','']);const [preferences,setPreferences]=useState('Bollywood movies from 2000 onward');const [rounds,setRounds]=useState(10);const [hintLimit,setHintLimit]=useState(3);const [timerSeconds,setTimerSeconds]=useState(120);const [loadedCardId,setLoadedCardId]=useState<string|null>(null);const [game,setGame]=useState<Game|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [guess,setGuess]=useState('');const [message,setMessage]=useState('');const [help,setHelp]=useState(false);const [exit,setExit]=useState(false);const [sound,setSound]=useState(false);const [seconds,setSeconds]=useState(120);const [restoring,setRestoring]=useState(true);const busyRef=useRef(false);const revision=useRef(0);const soundRef=useRef<AudioContext|null>(null);
 const card=game?.card;
 useEffect(()=>{const id=localStorage.getItem('movie-night-session');if(id)fetch(`/api/game?id=${id}`).then(r=>r.json()).then(data=>{if(data.id)setGame(data);else localStorage.removeItem('movie-night-session');}).catch(()=>setError('Could not reconnect to your game.')).finally(()=>setRestoring(false));else setRestoring(false);},[]);
 useEffect(()=>{if(!game||game.ended)return;const id=setInterval(async()=>{if(busyRef.current)return;const version=revision.current;try{const res=await fetch(`/api/game?id=${game.id}`);const data=await res.json();if(res.ok&&!busyRef.current&&version===revision.current)setGame(data);}catch{/* next poll reconnects */}},2500);return()=>clearInterval(id);},[game?.id,game?.ended]);
 useEffect(()=>{setSeconds(game?.timerSeconds??120);setGuess('');setMessage('');},[card?.id,game?.timerSeconds]);
 useEffect(()=>{const limit=game?.timerSeconds??120;if(!card||card.status!=='ready'||card.revealed||loadedCardId!==card.id||limit===0)return;const key=`movie-night-timer-${card.id}`;const saved=Number(localStorage.getItem(key));const start=saved>0?saved:Date.now();localStorage.setItem(key,String(start));const tick=()=>setSeconds(Math.max(0,limit-Math.floor((Date.now()-start)/1000)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer);},[card?.id,card?.status,card?.revealed,game?.timerSeconds,loadedCardId]);
 useEffect(()=>{if(!help&&!exit)return;const previous=document.activeElement as HTMLElement;const modal=document.querySelector<HTMLElement>('.modal');const controls=()=>Array.from(modal?.querySelectorAll<HTMLElement>('button:not(:disabled), [href], input, select, textarea, [tabindex="0"]')??[]);controls()[0]?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setHelp(false);setExit(false);}if(e.key==='Tab'){const list=controls();if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};},[help,exit]);
 function chime(){if(!sound)return;try{const ctx=soundRef.current??=new AudioContext();void ctx.resume();[523,659,784].forEach((frequency,i)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=frequency;gain.gain.setValueAtTime(.09,ctx.currentTime+i*.12);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.12+.3);osc.start(ctx.currentTime+i*.12);osc.stop(ctx.currentTime+i*.12+.3);});}catch{}}
 async function send(action:string,extra:Record<string,unknown>={}){if(busyRef.current)return;busyRef.current=true;revision.current++;setBusy(true);setError('');try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:game?.id,cardId:card?.id,action,...extra})});const data=await res.json();if(!res.ok)throw new Error(data.error);setGame(data);localStorage.setItem('movie-night-session',data.id);if(data.verdict==='correct'){setMessage('That’s a wrap. You got it!');chime();}else if(data.verdict==='incorrect'){setMessage('Not quite! Take another look.');setGuess('');}else if(data.verdict==='clarify')setMessage('Almost specific enough—try the full movie title.');return true;}catch(e){setError(e instanceof Error?e.message:'Could not connect. Please retry.');return false;}finally{busyRef.current=false;setBusy(false);}}
 function reset(){revision.current++;localStorage.removeItem('movie-night-session');setGame(null);setError('');setMessage('');setExit(false);}
 const maxScore=game?Math.max(...game.players.map(p=>p.score)):0;
 return <main>
 <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
 <header className="header"><a className="brand" href="/" aria-label="Guess the Movie home"><span className="brand-icon"><Popcorn size={45} strokeWidth={1.7}/></span><span>Guess<span className="brand-bottom">the Movie<span className="brand-dot">.</span></span></span></a><div className="header-right"><span className="local-badge"><i/> THE LIVING ROOM EDITION</span><button className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button" aria-label="How to play" onClick={()=>setHelp(true)}><HelpCircle size={21}/></button>{game&&!game.ended&&<button className="exit-button" onClick={()=>setExit(true)}><LogOut size={17}/> Exit</button>}</div></header>
 {restoring?<div className="loading-page"><LoaderCircle className="spin"/> Setting the scene…</div>:!game?<>
 <section className="intro"><div className="eyebrow"><span/> LESS CLUES. MORE “I KNOW THIS ONE!” <span/></div><h1>Your people. <em>Your movie night.</em></h1><p>One picture. Endless possibilities. Who’s the biggest movie buff?</p></section>
 <div className="setup-scene"><div className="side-doodle left-doodle"><Clapperboard size={105} strokeWidth={1.1}/><span>LIGHTS, CAMERA…<br/>a little friendly rivalry.</span><div className="mini-ticket"><Ticket size={26}/> ADMIT EVERYONE</div></div>
 <form className="setup-panel" onSubmit={e=>{e.preventDefault();void send('create',{players:names.filter(n=>n.trim()).map(n=>n.trim()),preferences,rounds,hintLimit,timerSeconds});}}>
 <section className="setup-section"><div className="section-heading"><span className="step">01</span><div><h2>Who’s watching?</h2><p>Add your cast of characters. 2–6 is a great crowd.</p></div><span className="section-label">THE CAST</span></div><div className="players-grid">{names.map((name,i)=><div className={`player-input tint-${i%6}`} key={i}><span className="avatar">{avatars[i]}</span><input aria-label={`Player ${i+1} name`} placeholder={`Player ${i+1}`} maxLength={24} value={name} onChange={e=>setNames(names.map((n,j)=>j===i?e.target.value:n))}/><button type="button" aria-label={`Remove player ${i+1}`} onClick={()=>setNames(names.filter((_,j)=>i!==j))} disabled={names.length===1}><X size={16}/></button></div>)}{names.length<8&&<button className="add-player" type="button" onClick={()=>setNames([...names,''])}><Plus size={18}/> Add player</button>}</div></section>
 <section className="setup-section"><div className="section-heading"><span className="step">02</span><div><h2>Set the scene</h2><p>What kind of movies are you in the mood for?</p></div><span className="section-label">YOUR VIBE</span></div><div className="preference-field"><Clapperboard size={23}/><textarea aria-label="Movie preferences" placeholder="e.g. Bollywood after 2000, only thrillers, or 90s Hollywood" maxLength={1000} rows={2} value={preferences} onChange={e=>setPreferences(e.target.value)}/><Sparkles size={18}/></div><div className="preference-note">Choose a film industry, era or genre. Leave the rest to us.</div></section>
 <section className="setup-section last"><div className="section-heading"><span className="step">03</span><div><h2>Make it your night</h2><p>A quick round or a full feature? You decide.</p></div><span className="section-label">THE RULES</span></div><div className="settings-grid"><label>Number of rounds<select value={rounds} onChange={e=>setRounds(Number(e.target.value))}>{[5,10,15,20,30].map(n=><option key={n} value={n}>{n} rounds {n===10?'· the sweet spot':''}</option>)}</select></label><label>Hints per round<select value={hintLimit} onChange={e=>setHintLimit(Number(e.target.value))}>{[0,1,2,3].map(n=><option key={n} value={n}>{n===0?'No hints · feeling brave':`Up to ${n} hint${n>1?'s':''}`}</option>)}</select></label><label>Round timer<select value={timerSeconds} onChange={e=>setTimerSeconds(Number(e.target.value))}>{[30,60,120,180,300,0].map(n=><option key={n} value={n}>{n===0?"No timer":n<60?`${n} seconds`:`${n/60} min${n===60?"":"s"}${n===120?" · default":""}`}</option>)}</select></label></div></section>
 {error&&<div className="error" role="alert">{error}</div>}<div className="start-row"><span><span className="tiny-dot"/> One screen. Everyone plays.</span><button className="primary start" disabled={busy||!names.some(n=>n.trim())}>{busy?<LoaderCircle className="spin" size={19}/>:<Play size={18} fill="currentColor"/>}{busy?'Setting the scene…':'Let’s play'}<ArrowRight size={19}/></button></div>
 </form><div className="side-doodle right-doodle"><div className="poster"><Film size={35}/><strong>JUST<br/>ONE MORE<br/><em>MOVIE.</em></strong><span>THE BEST NIGHTS START HERE</span></div><Popcorn className="popcorn-doodle" size={108} strokeWidth={1.2}/></div></div>
 <footer><Sparkles size={14}/> A fresh visual riddle every round. Made for your kind of movies.</footer>
 </>:game.ended?<section className="results"><div className="result-icon">🏆</div><div className="eyebrow">THE CREDITS ARE ROLLING</div><h1>{maxScore===0?'What a movie night!':game.players.filter(p=>p.score===maxScore).map(p=>p.name).join(' & ')+(game.players.filter(p=>p.score===maxScore).length===1?' takes the spotlight!':' share the spotlight!')}</h1><p>Good movies. Better company. Here’s the final cut.</p><div className="final-scores">{[...game.players].sort((a,b)=>b.score-a.score).map((p,i)=><div key={p.name}><span>{i===0&&maxScore>0?'👑':`${i+1}.`} {p.name}</span><strong>{p.score} <small>pts</small></strong></div>)}</div><button className="primary" onClick={reset}><RotateCcw size={18}/> Another movie night</button></section>:<section className="game-layout">
 <aside className="scoreboard"><div className="eyebrow">THE CAST <Trophy size={14}/></div>{game.players.map((p,i)=><div className={`score-player tint-${i%6}`} key={p.name}><span className="avatar">{avatars[i]}</span><div><strong>{p.name}</strong><span>{p.score} <small>points</small></span></div>{p.score===maxScore&&maxScore>0&&<span className="crown">👑</span>}</div>)}<div className="score-note">A correct guess.<br/>A well-earned point.</div></aside>
 <div className="play-area"><div className="round-bar"><div><span className="eyebrow">NOW SHOWING</span><h2>Round {game.index+1} <span>/ {game.rounds}</span></h2></div><div className="round-progress"><div style={{width:`${(game.index+1)/game.rounds*100}%`}}/></div><div className={`timer ${game.timerSeconds!==0&&seconds===0?"time-up":""}`} aria-label="Time remaining"><Clock size={18}/>{game.timerSeconds===0?"No timer":`${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`}</div></div>
 <div className={`movie-card ${card?.revealed?'revealed':''}`} key={card?.id||'waiting'}><span className="card-corner">GUESS THE MOVIE</span>{card?.status==='ready'?<>{/* Generated clue intentionally has no answer-bearing alt text. */}<img src={card.image!} onLoad={()=>setLoadedCardId(card.id)} alt="Visual movie riddle. Discuss the illustrated clues and guess the movie."/>{card.revealed&&<div className="answer-overlay"><div className="answer-tag">{card.solved?<><Check size={17}/> THAT’S THE ONE!</>:'THE BIG REVEAL'}</div><h2>{card.answer?.title}</h2><span>{card.answer?.year}</span><p>{card.answer?.explanation}</p></div>}</>:<div className="card-loading">{card?.status==='error'||game.error?<><Clapperboard size={48}/><h2>A small intermission</h2><p>{card?.error||game.error}</p><button className="secondary" disabled={busy} onClick={()=>void send('retry')}><RotateCcw size={17}/> Try again</button></>:<><div className="loading-reel"><Film size={54}/></div><h2>Setting the scene…</h2><p>Dreaming up a movie. Drawing your clues.<br/>The first card can take a minute or two.</p><div className="loading-dots"><i/><i/><i/></div></>}</div>}<span className="card-number">{String(game.index+1).padStart(2,'0')} / THE VISUAL EDITION</span></div>
 {card?.status==='ready'&&!card.revealed&&<><div className="hint-row">{Array.from({length:game.hintLimit},(_,i)=><button key={i} className={`hint ${card.hints[i]?'open':''}`} disabled={busy||i>card.hints.length||Boolean(card.hints[i])} onClick={()=>void send('hint')}><Lightbulb size={23}/><span><strong>Hint {i+1}</strong><small>{card.hints[i]||['A little nudge','Get a little closer','The final clue'][i]}</small></span>{!card.hints[i]&&<Plus size={15}/>}</button>)}</div><form className="guess-form" onSubmit={e=>{e.preventDefault();void send('guess',{guess});}}><input autoComplete="off" aria-label="Your movie guess" placeholder="Wait… I know this movie!" maxLength={200} value={guess} onChange={e=>setGuess(e.target.value)}/><button className="primary purple" disabled={busy||!guess.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<>Submit guess <ArrowRight size={18}/></>}</button></form><div className="guess-message" aria-live="polite">{message||(game.timerSeconds!==0&&seconds===0?'Time’s up! Take one last guess or reveal the answer.':'Say it out loud. Type it in. Claim your moment.')}</div><button className="reveal-button" disabled={busy} onClick={()=>void send('reveal')}><Lightbulb size={17}/> Reveal answer <span>· no points</span></button></>}
 {card?.revealed&&<div className="award-panel">{card.solved&&!card.awarded?<><h3>Who called it?</h3><p>Give the star of this round their point.</p><div className="award-players">{game.players.map((p,i)=><button key={p.name} disabled={busy} onClick={()=>void send('award',{player:i})}><span>{avatars[i]}</span>{p.name}<Plus size={14}/></button>)}</div></>:<><p>{card.awarded?'A point on the board. Ready for another?':'A good one for your watchlist. On to the next!'}</p><button className="primary" disabled={busy} onClick={()=>void send('next')}>{game.index+1===game.rounds?'See the final scores':'Next movie'}<ArrowRight size={18}/></button></>}</div>}
 {error&&<div className="error" role="alert">{error}</div>}{game.error&&card?.status==='ready'&&<div className="error">Upcoming cards: {game.error} <button disabled={busy} onClick={()=>void send('retry')}>Retry</button></div>}<div className="queue-status"><span className="tiny-dot"/>{game.queue>0?`${game.queue} upcoming ${game.queue===1?'card is':'cards are'} ready` : game.index+1===game.rounds?'The final scene': 'Preparing your next movie moments'}</div></div>
 </section>}
 {(help||exit)&&<div className="modal-backdrop" onClick={()=>{setHelp(false);setExit(false);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>{setHelp(false);setExit(false);}}><X size={20}/></button>{help?<><Popcorn size={42}/><h2 id="modal-title">Everyone’s a movie critic.<br/>Time to prove it.</h2><ol><li>Look at the picture together. Every detail could be a clue.</li><li>Type a movie title. A wrong guess keeps the card in play.</li><li>Need a nudge? Open a hint—or reveal and skip the point.</li><li>Got it? Pick who answered and give them one point.</li></ol><p>The timer starts when the picture loads. At zero, you can still finish a guess or reveal the answer.</p><button className="primary" onClick={()=>setHelp(false)}>Got it. Roll camera!</button></>:<><h2 id="modal-title">Call it a night?</h2><p>End this game and see everyone’s scores. Upcoming card generation will stop.</p><div className="modal-actions"><button className="secondary" onClick={()=>setExit(false)}>Keep playing</button><button className="primary" disabled={busy} onClick={async()=>{if(await send('end'))setExit(false);}}>End game</button></div></>}</section></div>}
 </main>
}
