import { promises as fs } from 'node:fs';
import path from 'node:path';
import { concept, generate, judge, type Concept } from './gemini';
export type Card={id:string,concept:Concept,status:'pending'|'ready'|'error',mime?:string,error?:string,hints:number,revealed:boolean,solved:boolean,awarded:boolean};
export type Game={id:string,players:{name:string,score:number}[],preferences:string,rounds:number,hintLimit:number,timerSeconds?:number,index:number,cards:Card[],ended:boolean,error?:string};
const root=path.join(process.cwd(),'.data');
const g=globalThis as typeof globalThis & {movieGames?:Map<string,Game>,movieJobs?:Set<string>,movieLocks?:Set<string>,movieImages?:Set<string>,movieSaves?:Map<string,Promise<void>>};
const games=g.movieGames??=new Map<string,Game>();const jobs=g.movieJobs??=new Set<string>();const locks=g.movieLocks??=new Set<string>();const images=g.movieImages??=new Set<string>();
const valid=(id:string)=>/^[a-f0-9-]{36}$/.test(id);
const saves=g.movieSaves??=new Map<string,Promise<void>>();
export async function save(game:Game){const snapshot=JSON.stringify(game);const previous=saves.get(game.id)??Promise.resolve();const next=previous.catch(()=>{}).then(async()=>{await fs.mkdir(root,{recursive:true});const temp=path.join(root,`${game.id}.${crypto.randomUUID()}.tmp`);await fs.writeFile(temp,snapshot);await fs.rename(temp,path.join(root,game.id+'.json'));});saves.set(game.id,next);try{await next;}finally{if(saves.get(game.id)===next)saves.delete(game.id);}}
export async function getGame(id:string){if(!valid(id))throw new Error('Invalid game.');if(games.has(id))return games.get(id)!;try{const game:Game=JSON.parse(await fs.readFile(path.join(root,id+'.json'),'utf8'));games.set(id,game);return game;}catch{throw new Error('This game could not be found. Start a new game.');}}
export function publicGame(game:Game){const c=game.cards[game.index];return {id:game.id,players:game.players,preferences:game.preferences,rounds:game.rounds,hintLimit:game.hintLimit,timerSeconds:game.timerSeconds??120,index:game.index,ended:game.ended,error:game.error,queue:game.cards.slice(game.index+1).filter(c=>c.status==='ready').length,card:c?{id:c.id,status:c.status,error:c.error,image:c.status==='ready'?`/api/image?game=${game.id}&card=${c.id}`:null,hints:c.concept.hints.slice(0,c.hints),revealed:c.revealed,solved:c.solved,awarded:c.awarded,answer:c.revealed?{title:c.concept.title,year:c.concept.year,explanation:c.concept.explanation}:null}:null};}
export async function createGame(input:{players:string[],preferences:string,rounds:number,hintLimit:number,timerSeconds?:number}){if(!process.env.GEMINI_API_KEY)throw new Error('Add GEMINI_API_KEY to .env.local and restart the server to start playing.');const game:Game={...input,id:crypto.randomUUID(),players:input.players.map(name=>({name,score:0})),index:0,cards:[],ended:false};games.set(game.id,game);await save(game);fill(game);return publicGame(game);}
async function render(game:Game,c:Card){if(images.has(c.id)||game.ended)return;images.add(c.id);try{const result=await generate(process.env.GEMINI_IMAGE_MODEL||'gemini-2.5-flash-image-preview','Render only the described visual movie riddle. No text, typography, letters, logos, titles or watermarks. Minimal visual elements on a warm ivory background.',c.concept.imagePrompt,true);await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,c.id+'.image'),Buffer.from(result.data,'base64'));c.mime=result.mimeType;c.status='ready';delete c.error;}catch(e){c.status='error';c.error=e instanceof Error?e.message:'Image generation failed.';}finally{images.delete(c.id);await save(game);}}
export function fill(game:Game){if(game.ended||jobs.has(game.id)||game.error)return;jobs.add(game.id);void(async()=>{try{for(const c of game.cards.slice(game.index,game.index+4)){if(c.status==='pending')void render(game,c);}
 while(!game.ended&&game.cards.length<Math.min(game.rounds,game.index+4)){
 let selected:Concept|undefined;
 for(let attempt=0;attempt<3;attempt++){const candidate=await concept(game.preferences,game.cards.map(c=>c.concept));const normalize=(s:string)=>s.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');if(!game.cards.some(c=>c.concept.year===candidate.year&&[c.concept.title,...c.concept.aliases].some(title=>[candidate.title,...candidate.aliases].some(other=>normalize(title)===normalize(other))))){selected=candidate;break;}}
 if(game.ended)break;if(!selected)throw new Error('The director repeated a movie. Retry for a fresh pick.');
 const c:Card={id:crypto.randomUUID(),concept:selected,status:'pending',hints:0,revealed:false,solved:false,awarded:false};game.cards.push(c);await save(game);void render(game,c);
 }
 }catch(e){game.error=e instanceof Error?e.message:'Could not prepare a movie.';await save(game);}finally{jobs.delete(game.id);}})();}
export async function action(game:Game,input:{action:string,cardId?:string,guess?:string,player?:number}){if(locks.has(game.id))throw new Error('One moment—your previous action is still processing.');locks.add(game.id);let verdict:string|undefined;try{if(input.action==='end'){game.ended=true;}else {if(game.ended)throw new Error('This game has finished.');const c=game.cards[game.index];if(input.action==='retry'){delete game.error;if(c?.status==='error'){c.status='pending';delete c.error;}fill(game);}else {if(!c||c.id!==input.cardId||c.status!=='ready')throw new Error('This card is not ready.');switch(input.action){case 'guess':if(c.revealed)throw new Error('This answer has already been revealed.');verdict=await judge(c.concept,input.guess||'');if(verdict==='correct'){c.solved=true;c.revealed=true;}break;case 'hint':if(!c.revealed)c.hints=Math.min(game.hintLimit,c.hints+1);break;case 'reveal':c.revealed=true;break;case 'award':if(!c.solved||c.awarded||!game.players[input.player!])throw new Error('That point cannot be awarded.');game.players[input.player!].score++;c.awarded=true;break;case 'next':if(!c.revealed||c.solved&&!c.awarded)throw new Error('Reveal the answer and award any earned point first.');game.index++;if(game.index>=game.rounds)game.ended=true;else fill(game);break;default:throw new Error('Unknown action.');}}}await save(game);return {...publicGame(game),verdict};}finally{locks.delete(game.id);}}
export async function imageData(gameId:string,cardId:string){const game=await getGame(gameId);const card=game.cards.find(c=>c.id===cardId);if(!card||card.status!=='ready'||!valid(cardId))throw new Error('Image not ready.');return {data:await fs.readFile(path.join(root,cardId+'.image')),mime:card.mime||'image/png'};}
